apiVersion: v1
kind: Pod
metadata:
    name: busybox1
    namespace: default
spec:
    containers:
      - name: busybox1
        image: docker.io/busybox:latest
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
    restartPolicy: Always
